/**
 * GENERATED by tools/cn-font-catalog/src/build.mjs — 请勿手改，重跑管线更新。
 * 构建日期：2026-09-25 | 目录规模：合并后 81 族收录 / 17 条字重拆族别名
 *
 * T42 S1：中文网字计划全量目录（registry 精选 6 族之外的 @chinese-fonts/* 包）。
 * catalog 族白名单语义 = 默认停用（opt-in，D-c）；授权以包内 license 原文为准，未审计（D-d）。
 *
 * 字重聚合：同包内、族名仅差一个词表字重后缀（空格/连字符分隔；词表 =
 * extralight/ultralight/semibold/demibold/extrabold/ultrabold/thin/light/regular
 * /normal/medium/bold/black/heavy，长词优先匹配）者并为一组，base = 去后缀名。
 * 旧族名以 LEGACY_CN_FAMILY_ALIAS 兜底（picker 持久化恢复兼容），两函数查询
 * 自动跳别名指向合并条目。
 */

export interface CnFontCatalogEntry {
  family: string
  /** 中文显示名（采自 dist 子族目录名，四条全满足才填：①dir 恰解 1 family；②该 family 在本包仅来自此 dir；③dir 含 CJK；④dir ≠ family）。展示用，family 身份不变 */
  displayName?: string
  package: string
  /** 构建时实解版本（钉扎可重现 + piece 缓存键稳定，D-g） */
  version: string
  /** npm 包内 license 字段原文（未审计，展示用） */
  license: string
  variable: boolean
  /** result.css 实见字重（静态档集合；VF 为区间端点） */
  weights: number[]
  /** CDN base 覆盖（缺省 = jsdelivr）；运行时透传 descriptor.baseURL。2026-09-06 复测 jsdelivr 已支持非 ASCII 路径（37/37 族全绿），全量目录零回退 */
  base?: string
}

export const CN_FONT_CATALOG: CnFontCatalogEntry[] = [
  {
    family: '荆南俊俊体',
    package: '@chinese-fonts/jnjj',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [700]
  },
  {
    family: '快看世界体',
    package: '@chinese-fonts/kksjt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: '平方赖江湖飞扬体',
    package: '@chinese-fonts/pfljhfyt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: '平方赖江湖琅琊体',
    package: '@chinese-fonts/pfljhlyt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: '瑞美加张清平硬笔行书',
    package: '@chinese-fonts/rmjzqpybxs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: '峄山碑篆体',
    package: '@chinese-fonts/ysbzt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'bailubangbangshouxieti',
    package: '@chinese-fonts/blbbsxt',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '白路棒棒手写体'
  },
  {
    family: 'BWCKKT',
    package: '@chinese-fonts/bwckkt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [300, 400, 700]
  },
  {
    family: 'CEF Fonts CJK',
    package: '@chinese-fonts/cef',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'CEF Fonts CJK Mono',
    package: '@chinese-fonts/cef',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'chengrongguangke',
    package: '@chinese-fonts/crgkk',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '程荣光刻楷'
  },
  {
    family: 'Child Fun Sans Demo',
    package: '@chinese-fonts/yqt',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'Cubic 11',
    package: '@chinese-fonts/cubic',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'Douyin Sans',
    package: '@chinese-fonts/dymh',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [700]
  },
  {
    family: 'DOUYU Font',
    package: '@chinese-fonts/dyzgt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '斗鱼追光体'
  },
  {
    family: 'FlyFlowerSong',
    package: '@chinese-fonts/fhst',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '飞花宋体'
  },
  {
    family: 'FontQu Smile 常规',
    package: '@chinese-fonts/zzqxmxht',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '字制区喜脉喜欢体'
  },
  {
    family: 'GuanKiapTsingKhai',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-90',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-S',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-S-90',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-T',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-T-90',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-TW',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-TW-90',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-W',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-W-90',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'hongleixingshu',
    package: '@chinese-fonts/hlxsjt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '鸿雷行书简体'
  },
  {
    family: 'Huiwen-mincho',
    package: '@chinese-fonts/hwmct',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '汇文明朝体'
  },
  {
    family: 'jiangxizhuokai',
    package: '@chinese-fonts/jxzk',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '江西拙楷'
  },
  {
    family: 'LogoSC LongZhuTi',
    package: '@chinese-fonts/bxzlzt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '标小智龙珠体'
  },
  {
    family: 'Long Cang',
    package: '@chinese-fonts/yzklct',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '有字库龙藏体'
  },
  {
    family: 'LXGW Bright',
    package: '@chinese-fonts/lxgwwenkaibright',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300, 400, 500]
  },
  {
    family: 'LXGW Marker Gothic',
    package: '@chinese-fonts/lxgwmanhei',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'LXGW Neo ZhiSong',
    package: '@chinese-fonts/lxgw-neo-zhi-song',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'LXGW WenKai Mono Screen',
    package: '@chinese-fonts/lywkpmydb',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'LXGW WenKai Screen',
    package: '@chinese-fonts/lywkpmydb',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'MaoKenTangYuan (beta)',
    package: '@chinese-fonts/mkwtyt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'MaokenZhuyuanTi',
    package: '@chinese-fonts/mkzyt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '猫啃珠圆体'
  },
  {
    family: 'Maple Mono CN',
    package: '@chinese-fonts/maple-mono-cn',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800]
  },
  {
    family: 'Moon Stars Kai',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300, 400, 700]
  },
  {
    family: 'Moon Stars Kai HW',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300, 400, 700]
  },
  {
    family: 'Moon Stars Kai T',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300, 400, 700]
  },
  {
    family: 'Moon Stars Kai T HW',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300, 400, 700]
  },
  {
    family: 'MuzaiPixel',
    package: '@chinese-fonts/mzxst',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'nzgrKangxi',
    package: '@chinese-fonts/rzjkxzdmh',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'nzgrRuYinZouZhangKai',
    package: '@chinese-fonts/rzjryzzk',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'PangMenZhengDao-XiXian',
    package: '@chinese-fonts/pmzdxxt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '庞门正道细线体'
  },
  {
    family: 'PING FANG GONG ZI TI',
    package: '@chinese-fonts/pfgzt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '平方公子体'
  },
  {
    family: 'PING FANG MENG MNEG DA',
    package: '@chinese-fonts/pfmmd',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '平方萌萌哒'
  },
  {
    family: 'QIJIFALLBACK',
    package: '@chinese-fonts/hldqjt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'QuanPixel 8px',
    package: '@chinese-fonts/qxs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'shetumodengxiaofangti',
    package: '@chinese-fonts/stmdxf',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '摄图摩登小方体'
  },
  {
    family: 'Slidefu',
    package: '@chinese-fonts/ysfxt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'Smiley Sans Oblique',
    package: '@chinese-fonts/dyh',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'SoukouMincho',
    package: '@chinese-fonts/zjmc',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '装甲明朝体'
  },
  {
    family: 'Source Han Serif CN for Display',
    package: '@chinese-fonts/sypxzs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '思源屏显臻宋'
  },
  {
    family: 'SuCaiJiShi-SheHuiTi',
    package: '@chinese-fonts/scjssh',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '素材集市社会体'
  },
  {
    family: 'The Peak Font 隨峰體 Beta',
    package: '@chinese-fonts/sft',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '随峰体'
  },
  {
    family: 'ToneOZ-Pinyin-Kai-Simplified',
    package: '@chinese-fonts/toneoz-pinyin-kai-simplified',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-Pinyin-Tsuipita-TC',
    package: '@chinese-fonts/toneoz-tsuipita',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-Pinyin-WenKai',
    package: '@chinese-fonts/toneoz-pinyin-wenkai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300, 400, 500]
  },
  {
    family: 'ToneOZ-PinyinW-Kai-Simplified',
    package: '@chinese-fonts/toneoz-pinyin-kai-simplified',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-RadicalZ-KaiTraditional',
    package: '@chinese-fonts/toneoz-radicalz-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-Tsuipita-TC',
    package: '@chinese-fonts/toneoz-tsuipita',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-YinPZ-Tsuipita-TC',
    package: '@chinese-fonts/toneoz-tsuipita',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-Zhuyin-Tsuipita-TC',
    package: '@chinese-fonts/toneoz-tsuipita',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'TsangerZhoukeZhengdabangshu',
    package: '@chinese-fonts/cezkzdbs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '仓耳周珂正大榜书'
  },
  {
    family: 'Xiaohe Simplify Sans VF',
    package: '@chinese-fonts/xiaohe-simplify',
    version: '2.0.0',
    license: 'MIT',
    variable: true,
    weights: [250, 900]
  },
  {
    family: 'Xiaohe Simplify Serif VF',
    package: '@chinese-fonts/xiaohe-simplify',
    version: '2.0.0',
    license: 'MIT',
    variable: true,
    weights: [250, 900]
  },
  {
    family: 'xiaowei',
    package: '@chinese-fonts/zkxw',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '站酷小薇LOGO体_猫啃网'
  },
  {
    family: 'XuandongKaishu',
    package: '@chinese-fonts/xuandongkaishu',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'YEFONTXiaoShiTou',
    package: '@chinese-fonts/yzgcxst',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '也字工厂小石头'
  },
  {
    family: 'YouSheBiaoTiHei',
    package: '@chinese-fonts/ysbth',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '优设标题黑'
  },
  {
    family: 'YouSheShaYuFeiTeJianKangTi',
    package: '@chinese-fonts/syftjkt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '优设鲨鱼菲特健康体'
  },
  {
    family: 'YuFanXinYu',
    package: '@chinese-fonts/yfxy',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [300, 400, 500, 700]
  },
  {
    family: 'YunFengchongqingbangbangti',
    package: '@chinese-fonts/cqscbbt',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'Zhi Mang Xing',
    package: '@chinese-fonts/zqzmxs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '钟齐志莽行书'
  },
  {
    family: 'Zhuque Fangsong (technical preview)',
    package: '@chinese-fonts/zqfs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'zihunbiantaoti',
    package: '@chinese-fonts/zhbtt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '字魂扁桃体'
  },
  {
    family: 'ZoomlaMengyas-A080',
    package: '@chinese-fonts/zlmyz',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    displayName: '逐浪萌芽字'
  }
]

export const LEGACY_CN_FAMILY_ALIAS: Record<string, string> = {
  'LXGW Bright Light': 'LXGW Bright',
  'LXGW Bright Medium': 'LXGW Bright',
  'Maple Mono CN ExtraBold': 'Maple Mono CN',
  'Maple Mono CN ExtraLight': 'Maple Mono CN',
  'Maple Mono CN Light': 'Maple Mono CN',
  'Maple Mono CN Medium': 'Maple Mono CN',
  'Maple Mono CN SemiBold': 'Maple Mono CN',
  'Maple Mono CN Thin': 'Maple Mono CN',
  'Moon Stars Kai HW Light': 'Moon Stars Kai HW',
  'Moon Stars Kai Light': 'Moon Stars Kai',
  'Moon Stars Kai T HW Light': 'Moon Stars Kai T HW',
  'Moon Stars Kai T Light': 'Moon Stars Kai T',
  'ToneOZ-Pinyin-WenKai-Light': 'ToneOZ-Pinyin-WenKai',
  'ToneOZ-Pinyin-WenKai-Medium': 'ToneOZ-Pinyin-WenKai',
  'ToneOZ-Pinyin-WenKai-Regular': 'ToneOZ-Pinyin-WenKai',
  'YuFanXinYu-Light': 'YuFanXinYu',
  'YuFanXinYu-Medium': 'YuFanXinYu'
}

const catalogByFamily = new Map(CN_FONT_CATALOG.map((entry) => [entry.family, entry]))

export function cnCatalogEntry(family: string): CnFontCatalogEntry | undefined {
  const direct = catalogByFamily.get(family)
  if (direct) return direct
  const aliased = LEGACY_CN_FAMILY_ALIAS[family]
  return aliased ? catalogByFamily.get(aliased) : undefined
}

export function isCnCatalogFamily(family: string): boolean {
  if (catalogByFamily.has(family)) return true
  const aliased = LEGACY_CN_FAMILY_ALIAS[family]
  return aliased !== undefined && catalogByFamily.has(aliased)
}
